MIN_WATCHERS_COUNT_SLIDES = ENV['MIN_WATCHERS_SLIDES'] || 10
MIN_WATCHERS_COUNT_BLOGS = ENV['MIN_WATCHERS_BLOGS'] || 0
MIN_WATCHERS_COUNT_FAQ = ENV['MIN_WATCHERS_FAQ'] || 0
MIN_WATCHERS_COUNT_VIDEOS = ENV['MIN_WATCHERS_VIDEOS'] || 0
MIN_WATCHERS_COUNT_NOTEWORTHY = ENV['MIN_WATCHERS_NOTEWORTHY'] || 0
MIN_WATCHERS_COUNT_TWEETERS = ENV['MIN_WATCHERS_TWEETERS'] || 0
