MIN_WATCHERS_COUNT_SLIDES = ENV['MIN_WATCHERS_SLIDES'] || 1000
MIN_WATCHERS_COUNT_BLOGS = ENV['MIN_WATCHERS_BLOGS'] || 10
MIN_WATCHERS_COUNT_FAQ = ENV['MIN_WATCHERS_FAQ'] || 1000
MIN_WATCHERS_COUNT_VIDEOS = ENV['MIN_WATCHERS_VIDEOS'] || 20
MIN_WATCHERS_COUNT_NOTEWORTHY = ENV['MIN_WATCHERS_NOTEWORTHY'] || 10
MIN_WATCHERS_COUNT_TWEETERS = ENV['MIN_WATCHERS_TWEETERS'] || 50
